[project]
name = "typst-conda"
authors = ["Adrian Freund <adrian@freund.io>"]
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "win-64", "osx-64", "osx-arm64"]

[feature.build.tasks]
build = "rattler-build build -c conda-forge -c https://prefix.dev/typst-forge --recipe "
install-rattler-build = """
git clone https://github.com/Hofer-Julian/rattler-build.git &&
cd rattler-build &&
git checkout feat/oidc-support &&
cargo install --bin rattler-build --locked --path .
"""

[feature.lint.dependencies]
actionlint = "*"
check-jsonschema = "*"
shellcheck = "*"

[feature.pre-commit.dependencies]
pre-commit = "*"

[feature.pre-commit.tasks]
pre-commit-install = "pre-commit install"
lint = "pre-commit run -a"

[environments]
default = ["build", "lint", "pre-commit"]
build = ["build"]
pre-commit = ["pre-commit"]
lint = ["lint"]
